name: Terraform Apply (develop)

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: develop
    timeout-minutes: 3

    defaults:
      run:
        shell: bash
        working-directory: ${{ vars.TF_ACTIONS_WORKING_DIR }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform fmt
        run: terraform fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Download plan file from S3
        env:
          TF_PLAN_S3_BUCKET_NAME: ${{ vars.TF_PLAN_S3_BUCKET_NAME }}
          TF_PLAN_S3_OBJECT_PREFIX: ${{ vars.TF_PLAN_S3_OBJECT_PREFIX }}
        run:
          aws s3 cp s3://${TF_PLAN_S3_BUCKET_NAME}/${TF_PLAN_S3_OBJECT_PREFIX}/tfplan.binary tfplan.binary
      
      - name: Terraform Apply
        run: terraform apply -no-color -input=false -auto-approve tfplan.binary
