name: Terraform Apply (develop)

on:
  push:
    branches:
      - main

env:
  TF_PLAN_S3_BUCKET_NAME: ${{ vars.TF_PLAN_S3_BUCKET_NAME }}
  TF_PLAN_S3_OBJECT_PREFIX: ${{ vars.TF_PLAN_S3_OBJECT_PREFIX }}
  TFCMT_VERSION: 4.3.0

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: develop
    timeout-minutes: 3

    defaults:
      run:
        shell: bash
        working-directory: ${{ vars.TF_ACTIONS_WORKING_DIR }}

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup tfcmt
        run: |
          curl -OL https://github.com/suzuki-shunsuke/tfcmt/releases/download/v${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz
          tar xzf tfcmt_linux_amd64.tar.gz -C /usr/local/bin/

      - name: Terraform Init
        run: terraform init

      - name: Download plan file from S3
        run:
          aws s3 cp s3://${TF_PLAN_S3_BUCKET_NAME}/${TF_PLAN_S3_OBJECT_PREFIX}/tfplan.binary tfplan.binary
      
      - name: Terraform Apply
        run: tfcmt apply -- terraform apply -no-color -input=false -auto-approve tfplan.binary
